apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
